#!/usr/bin/env bash
# Auto-generated by The 36 Guilds
# Template: 🏢 现代IT公司 (Modern IT Company)
# Generated at: 2026-03-11T14:51:37.199730
set -euo pipefail

echo "============================================"
echo "🏢 Installing: 现代IT公司 (Modern IT Company)"
echo "  Agents: 8"
echo "  Stages: 6"
echo "============================================"

if ! command -v openclaw &>/dev/null; then
    echo "⚠️  openclaw CLI not found. Skipping agent registration."
    echo "   Workspaces and SOUL.md files will still be created."
    SKIP_REGISTER=1
else
    SKIP_REGISTER=0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_DIR="${SCRIPT_DIR}/agent_workspaces"

echo ""
echo "📁 Creating agent workspaces..."
mkdir -p "${WORKSPACE_DIR}/cto"
echo "  ✅ 👔 CTO (cto)"
mkdir -p "${WORKSPACE_DIR}/product_manager"
echo "  ✅ 📋 产品经理 (product_manager)"
mkdir -p "${WORKSPACE_DIR}/tech_lead"
echo "  ✅ 🏗️ 技术负责人 (tech_lead)"
mkdir -p "${WORKSPACE_DIR}/project_manager"
echo "  ✅ 📊 项目经理 (project_manager)"
mkdir -p "${WORKSPACE_DIR}/frontend_dev"
echo "  ✅ 🎨 前端工程师 (frontend_dev)"
mkdir -p "${WORKSPACE_DIR}/backend_dev"
echo "  ✅ ⚙️ 后端工程师 (backend_dev)"
mkdir -p "${WORKSPACE_DIR}/devops"
echo "  ✅ 🔧 DevOps 工程师 (devops)"
mkdir -p "${WORKSPACE_DIR}/qa_engineer"
echo "  ✅ 🧪 QA 工程师 (qa_engineer)"

echo ""
echo "📜 SOUL.md files are in place."

if [ "$SKIP_REGISTER" -eq 0 ]; then
    echo ""
    echo "🔧 Registering agents with OpenClaw..."
    openclaw agent create --id cto --name "👔 CTO" --workspace "${WORKSPACE_DIR}/cto" --contacts "product_manager" 2>/dev/null || echo "    ⚠️  Agent cto may already exist, skipping."
    openclaw agent create --id product_manager --name "📋 产品经理" --workspace "${WORKSPACE_DIR}/product_manager" --contacts "cto,tech_lead,project_manager" 2>/dev/null || echo "    ⚠️  Agent product_manager may already exist, skipping."
    openclaw agent create --id tech_lead --name "🏗️ 技术负责人" --workspace "${WORKSPACE_DIR}/tech_lead" --contacts "cto,product_manager" 2>/dev/null || echo "    ⚠️  Agent tech_lead may already exist, skipping."
    openclaw agent create --id project_manager --name "📊 项目经理" --workspace "${WORKSPACE_DIR}/project_manager" --contacts "cto,product_manager,frontend_dev,backend_dev,devops,qa_engineer" 2>/dev/null || echo "    ⚠️  Agent project_manager may already exist, skipping."
    openclaw agent create --id frontend_dev --name "🎨 前端工程师" --workspace "${WORKSPACE_DIR}/frontend_dev" --contacts "project_manager" 2>/dev/null || echo "    ⚠️  Agent frontend_dev may already exist, skipping."
    openclaw agent create --id backend_dev --name "⚙️ 后端工程师" --workspace "${WORKSPACE_DIR}/backend_dev" --contacts "project_manager" 2>/dev/null || echo "    ⚠️  Agent backend_dev may already exist, skipping."
    openclaw agent create --id devops --name "🔧 DevOps 工程师" --workspace "${WORKSPACE_DIR}/devops" --contacts "project_manager" 2>/dev/null || echo "    ⚠️  Agent devops may already exist, skipping."
    openclaw agent create --id qa_engineer --name "🧪 QA 工程师" --workspace "${WORKSPACE_DIR}/qa_engineer" --contacts "project_manager,cto" 2>/dev/null || echo "    ⚠️  Agent qa_engineer may already exist, skipping."

    echo ""
    echo "🔄 Restarting OpenClaw gateway..."
    openclaw gateway restart 2>/dev/null || echo "    ⚠️  Gateway restart skipped."
fi

echo ""
echo "============================================"
echo "✅ 🏢 现代IT公司 setup complete!"
echo ""
echo "Next steps:"
echo "  1. Review SOUL.md files in agent_workspaces/"
echo "  2. Customize agent models in config/agents.yaml"
echo "  3. Start your system"
echo "============================================"
